AWSTemplateFormatVersion: 2010-09-09

Resources:
  AgentActivation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        Fn::Join:
        - ""
        - - "https://"
          - "nemoseax"
          - ".s3.amazonaws.com/"
          - ""
          - "challenges/workload_security/templates/agent_activation.yaml"

  SetSNSandPolicyconfig:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        Fn::Join:
        - ""
        - - "https://"
          - "nemoseax"
          - ".s3.amazonaws.com/"
          - ""
          - "challenges/workload_security/templates/setSNSandPolicyconfig.yaml"
