AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TargetBucketName:
    Type: String

Resources:
  scoreTLSIC1WS:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies: 
        - PolicyName: ScoreTLSI
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "s3:ListBucket"
                Resource: 
                  - Fn::Join:
                    - ""
                    - - "arn:aws:s3:::"
                      - !Ref TargetBucketName

  C1WSScoreLambdaTLSI:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: C1WSScoreLambdaTLSI
      Code: 
        ZipFile: |
          import json, os
          import boto3
          #Print when loading function
          print('Loading function')
          def lambda_handler(event, context):
              s3 = boto3.client("s3")
              correct_answer_TLS = "1000763 - URI Length And Depth Restriction"
              print(event)
              keyword = event[0]["Reason"]
              print(keyword)
              if keyword == correct_answer_tls:
                  response = s3.put_object(
                  Bucket = os.environ['TARGETBucket'],
                  Key="tls_correct",  
                   )
              else:
                  print("do it again")
      Handler: index.lambda_handler
      Role: !GetAtt scoreroleTLSIC1WS.Arn
      Runtime: python3.7
      Timeout: 30
      Environment:
        Variables:
          TARGETBucket:
            Ref: TargetBucketName
    DependsOn:
      - scoreroleTLSIC1WS
Outputs:
  C1WSScoreLambdaTLSI:
    Value:
      Ref: C1WSScoreLambdaTLSI
