AWSTemplateFormatVersion: 2010-09-09
Description: >
  Tech Day C1WS day1 main Template
Parameters:
  # Bucket path related
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), dots(.) and forward slash (/).
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), dots(.) and
      forward slash (/).
    Type: String
  VPCID:
    Type: AWS::EC2::VPC::Id
  PublicSubnet1ID:
    Type: AWS::EC2::Subnet::Id
  AMIID:
    Type: String
  AttackerRole:
    Type: String
    Description: Shared IAM Role
    
Resources:
  ############################################ 
  ############# For EC2 Instance ############# 
  ############################################
  Agent:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}tlsi_ec2.yaml
      Parameters:
        VPC: !Ref VPCID
        PublicSubnet1: !Ref PublicSubnet1ID
        AllowIP: 0.0.0.0/0
        AMIID: !Ref AMIID

  attackerLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}tlsi_attacker.yaml
      Parameters:
        targetURL: !GetAtt Agent.Outputs.PublicDNS
        AttackerRole: !Ref AttackerRole
