AWSTemplateFormatVersion: 2010-09-09
Description: Shared common IAM Role for Lambda functions that only require AWSLambdaBasicExecutionRole

Resources:
  DefaultLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: {
            "Service": [
              "lambda.amazonaws.com",
              "ec2.amazonaws.com"
            ]
            }
          Action: ['sts:AssumeRole']
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies: 
        - PolicyName: ssmaccesspolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - ssm:DescribeParameters
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParameterHistory
                  - ssm:GetParametersByPath
                Resource: 
                  - arn:aws:ssm:*:*:parameter/player/C1/c1ApiKey
                  - arn:aws:ssm:*:*:parameter/player/C1/c1Region
                  - arn:aws:ssm:*:*:parameter/player/C1CS/clusterID

  DefaultLambdaExecutionRoleSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "DefaultLambdaExecutionRole"
      Value: !GetAtt DefaultLambdaExecutionRole.Arn
      Type: String

Outputs:
  SharedIamRoleArn:
    Value: !GetAtt DefaultLambdaExecutionRole.Arn
  SharedIAMRole:
    Value: !Ref DefaultLambdaExecutionRole 

  # Use it like this: '{{resolve:ssm:DefaultLambdaExecutionRole:1}}'