apiVersion: apps/v1
kind: Deployment
metadata:
  name: attacker-machine-deployment
  labels:
    app: attacker-machine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attacker-machine
  template:
    metadata:
      labels:
        app: attacker-machine
    spec:
      containers:
      - name: attacker-machine
        image: lscr.io/linuxserver/webtop:ubuntu-xfce
        env:
          - name: AUTO_LOGIN
            value: "false"
        ports:
          - containerPort: 3000
        startupProbe:
          exec:
            command:
            - cat
            - /config/startwm.sh
          initialDelaySeconds: 5
          periodSeconds: 5
        # Still need a liveness probe
---
apiVersion: v1
kind: Service
metadata:
  name: attacker-machine-service-loadbalancer
  labels:
    app: attacker-machine
spec:
  type: LoadBalancer
  selector:
    app: attacker-machine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000