kind: Service
metadata:
  name: attacker-machine-loadbalancer
  labels:
    app: attacker-machine
spec:
  type: LoadBalancer
  selector:
    app: attacker-machine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000