apiVersion: apps/v1
kind: Deployment
metadata:
  name: attacker-machine-deployment
  labels:
    app: attacker-machine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attacker-machine
  template:
    metadata:
      labels:
        app: attacker-machine
    spec:
      containers:
      - name: attacker-machine
        image: lscr.io/linuxserver/webtop:ubuntu-xfce
        env:
          - name: AUTO_LOGIN
            value: "false"
        ports:
          - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          failureThreshold: 3
          periodSeconds: 3
          initialDelaySeconds: 3
        startupProbe:
          httpGet:
            path: /
            port: 3000
          failureThreshold: 20
          periodSeconds: 10
          initialDelaySeconds: 3