apiVersion: v1
kind: Service
metadata:
  name: sudosingles-optimizer
  labels:
    app: log4shell
spec:
  type: ClusterIP
  selector:
    app: log4shell
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080