apiVersion: apps/v1
kind: Deployment
metadata:
  name: log4shell-deployment
  labels:
    app: log4shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log4shell
  template:
    metadata:
      labels:
        app: log4shell
    spec:
      containers:
      - name: vulnerable-app
        image: 255786373758.dkr.ecr.us-east-2.amazonaws.com/fss-attack:latest
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: "250m"
            memory: "128Mi"
