AWSTemplateFormatVersion: 2010-09-09
Description: >
  This service catalog for the Agent Version Control challenge (N-2).

Parameters:
  # Bucket path related
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: techday-2021-2
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), dots(.) and forward slash (/).
    Default: challenges/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), dots(.) and
      forward slash (/).
    Type: String
  PublicSubnet1SSMParameter:
    Default: "PublicSubnet1"
    Description: DO NOT CHANGE THIS VALUE
    Type: 'AWS::SSM::Parameter::Value<String>'
  LatestAmiId: 
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-windows-latest/Windows_Server-2016-English-Full-Base'
    Description: DO NOT CHANGE THIS VALUE
  c1ApiKeySSMKey:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: DO NOT CHANGE THIS VALUE
    Default: /player/C1/c1ApiKey
  c1RegionSSMKey:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /player/C1/c1Region
    Description: DO NOT CHANGE THIS VALUE

Resources:
  # Everything that needs to be created even before player starts playing.
  AVCWinBucket:
    Type: AWS::S3::Bucket
  WriteToV1BucketManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub Policy to write to ${AVCWinBucket}
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 's3:PutObject'
            Resource: !Sub 'arn:${AWS::Partition}:s3:::${AVCWinBucket}/*'
  CleanupBucketOnDelete:
    Type: Custom::cleanupBucket
    Properties:
      ServiceToken: !GetAtt 'CleanBucketFunction.Arn'
      BucketName: !Ref AVCWinBucket
      DependsOn: AVCWinBucket
  CleanBucketFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Cleans out Bucket during delete
      Handler: index.handler
      Runtime: python3.8
      Role: !GetAtt "CleanBucketRole.Arn"
      Timeout: 900
      Code:
        ZipFile: |
          import cfnresponse
          import logging
          import boto3
          import time
          status = cfnresponse.SUCCESS
          logger = logging.getLogger(__name__)
          logging.basicConfig(format='%(asctime)s %(message)s',level=logging.DEBUG)
          def handler(event, context):
              logger.debug(event)
              if event['RequestType'] == 'Delete':
                BUCKETNAME = event['ResourceProperties']['BucketName']
                s3 = boto3.resource('s3')
                time.sleep(240)
                bucket = s3.Bucket(BUCKETNAME)
                bucket_versioning = s3.BucketVersioning(BUCKETNAME)
                if bucket_versioning.status == 'Enabled':
                  bucket.object_versions.delete()
                else:
                  bucket.objects.all().delete()
                cfnresponse.send(event, context, status, {}, None)
              else:
                cfnresponse.send(event, context, status, {}, None)
  CleanBucketRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: lambda-bucketcleaner
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:DeleteObject
                  - s3:DeleteObjectVersion
                Resource: !Sub 'arn:${AWS::Partition}:s3:::${AVCWinBucket}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketVersioning
                Resource: !Sub 'arn:${AWS::Partition}:s3:::${AVCWinBucket}'
  AVCWinClientSSMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - !Ref WriteToV1BucketManagedPolicy
      Path: /

  AVCClientSSMProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - !Ref AVCWinClientSSMRole
      
  AVCWinInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref 'LatestAmiId'
      InstanceType: m6a.large
      IamInstanceProfile: !Ref AVCClientSSMProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId:
            Ref: PublicSubnet1SSMParameter
      Tags:
      - Key: Name
        Value: WinAVCClient
      UserData:
        Fn::Base64: !Sub |
          <powershell>
            Start-Transcript -path "c:\Projects\InstanceBuild.log"
            [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
            iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
            (New-Object System.Net.WebClient).DownloadFile("https://${QSS3BucketNameSSMValue}.s3.amazonaws.com/${QSS3KeyPrefixSSMValue}challenges/workload_security/agentversioncontrol/scripts/Projects.zip", "C:\Users\Administrator\Downloads\Projects.zip")
            Expand-Archive C:\Users\Administrator\Downloads\Projects.zip c:\
            Set-Content -Path 'C:\Projects\Bucket.txt' -Value '${AVCWinBucket}' -NoNewline
            Set-Content -Path 'C:\Projects\C1Region.txt' -Value '${c1RegionSSMKey}' -NoNewline
            Set-Content -Path 'C:\Projects\C1WSAPIKey.txt' -Value '${c1ApiKeySSMKey}' -NoNewline
            c:\Projects\AVCClientScript.ps1
            Stop-Transcript
          </powershell>
  TaskCheckCustomScript:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BucketName: !Ref AVCWinBucket
        ObjectNames: 'UpgradeTask.txt'
        ObjectPrefixes: ''
        ExpectedValues: 'True'
        FunctionName: 'AVC-Checker-Script'
      TemplateURL: !Sub 'https://${QSS3BucketNameSSMValue}.s3.amazonaws.com/${QSS3KeyPrefixSSMValue}challenges/workload_security/agentversioncontrol/templates/answer_checker.template.yaml'

#Outputs: