ssm_app_manager:
  should_upload: true
  documents_list:
    - document_name: AWSQuickStarts-AmazonEKS-Existing-VPC
      template_name: amazon-eks-entrypoint-existing-vpc.template.yaml
    - document_name: AWSQuickStarts-AmazonEKS
      template_name: amazon-eks-entrypoint-new-vpc.template.yaml
      has_nested_stacks: true
      nested_documents:
        - resource_name: VPCStack
          document_name: AWSQuickStarts-AWS-VPC