AWSTemplateFormatVersion: 2010-09-09
Description: Entrypoint for the File Storage Security challenge for tdc-2022-2. Copies lambda zip files and provides a sane, modular interface for challenge-specific development.

Parameters:
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: none
    Description: Update to where you hold the scripts. S3 bucket name for the SecJam assets. Quick Start bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/._]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: ""
    Description: Update to where you hold the scripts. S3 bucket name for the SecJam assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String

  # Define lambda code locations for challenge
  # A way to "define" variables for the environment. Do NOT change these, pls.
  ConformityCustomCheckCode:
    Default: "lambda/conformity_custom_check/conformity_custom_check.zip"
    Description: "DO NOT CHANGE FROM DEFAULT"
    Type: String


Resources:
  FSSMainStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - CopyZips
    Properties:
      Parameters:
        ChallengeBucket: !Ref QSS3BucketName
        ChallengeRoot: !Sub '${QSS3KeyPrefix}challenges/file_storage_security/'
        LambdaCodeBucket: !GetAtt CopyZipsStack.Outputs.DestinationBucket
        ConformityCustomCheckCode: !Ref ConformityCustomCheckCode
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}challenges/file_storage_security/templates/main.template.yaml'

  CopyZipsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        SourceBucket: !Ref QSS3BucketName
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}utils/copyzips/copyzips.template.yaml'
      TimeoutInMinutes: 10

  CopyZips:
    Type: Custom::CopyZips
    Properties:
      ServiceToken: !GetAtt 'CopyZipsStack.Outputs.FunctionArn'
      DestBucket: !GetAtt 'CopyZipsStack.Outputs.DestinationBucket'
      SourceBucket: !Ref QSS3BucketName
      Prefix: !Sub '${QSS3KeyPrefix}challenges/file_storage_security/'
      Objects:
      - !Ref ConformityCustomCheckCode
