AWSTemplateFormatVersion: 2010-09-09
Description: >
  Adds FSS CloudFormation templates to the Player's Service Catalog.

Parameters:
  ChallengeBucket:
    Description: Bucket for this challenge.
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Can include numbers, lowercase letters, uppercase letters, and hyphens (-).  It cannot start or end with a hyphen (-).
    Type: String
    Default: tdc-challenges
  ChallengeRoot:
    Description: Root folder for this challenge.
    AllowedPattern: ^[0-9a-zA-Z-/._]*$
    ConstraintDescription: Can include numbers, lowercase letters,
      uppercase letters, hyphens (-), dots(.) and forward slash (/).
    Default: ""
    Type: String
  # Service Catalog related
  PlayerServiceCatalogPortfolio:
    Type: String
  ServiceCatalogLaunchRoleArn:
    Type: String

Resources:
  # TODO I don't think we really need to do this .........
  FSSAllInOneServiceCatalogProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Description: This template create the All in One FSS stack deployment for the service catalog.
      Name: File Storage Security All in One Template
      Owner: Trend Micro
      ProvisioningArtifactParameters:
        - Info:
            LoadTemplateFromURL: !Sub 'https://${ChallengeBucket}.s3.amazonaws.com/${ChallengeRoot}templates/fss_allinone_service_catalog.template.yaml'

  FSSAllInOneProductID:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "FSSAllInOneProductID"
      Value: !Ref FSSAllInOneServiceCatalogProduct
      Type: String

  FSSAllInOneProductAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref PlayerServiceCatalogPortfolio
      ProductId: !Ref FSSAllInOneServiceCatalogProduct

  FSSAllInOneLaunchRoleConstraint:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    DependsOn: FSSAllInOneProductAssociation
    Properties:
      PortfolioId: !Ref PlayerServiceCatalogPortfolio
      ProductId: !Ref FSSAllInOneServiceCatalogProduct
      RoleArn: !Ref ServiceCatalogLaunchRoleArn  
