
AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template defines a the main stack for a challenge.

Resources:
  FSSAllInOneServiceCatalogProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Description: This template create the All in One FSS stack deployment for the service catalog.
      Name: File Storage Security All in One Template
      Owner: Trend Micro
      ProvisioningArtifactParameters:
        - Info:
            LoadTemplateFromURL: "https://raw.githubusercontent.com/trendmicro/cloudone-filestorage-deployment-templates/master/aws/FSS-All-In-One.template"

  FSSAllInOneProductID:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "FSSAllInOneProductID"
      Value: !Ref FSSAllInOneServiceCatalogProduct
      Type: String
