AWSTemplateFormatVersion: 2010-09-09
Description: >
  Adds FSS CloudFormation templates to the Player's Service Catalog.

Metadata:
  # cfn_lint: Disable warning for unused parameters
  cfn-lint:
    config:
      ignore_checks:
        - "W2001"

Parameters:
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription:
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: none
    Description:
      Update to where you hold the scripts. S3 bucket name for the Tech Day
      assets. Quick Start bucket name can include numbers, lowercase letters,
      uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/._]*$
    ConstraintDescription:
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    # REFERENCE (tdc-2022-2): Value in this file = latest/challenges/file_storage_security/templates/
    Default: ""
    Description:
      Update to where you hold the scripts. S3 bucket name for the Tech Day
      assets. Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Type: String
  # Service Catalog related
  PlayerServiceCatalogPortfolio:
    Type: String
  ServiceCatalogLaunchRoleArn:
    Type: String

Resources:
  # Service Catalog variables as SSM Parameters
  ChallengeBucket:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /player/FSS/ChallengeBucket
      Value: !Ref QSS3BucketName
      Type: String
      Description: Root bucket for FSS challenge
  SCTemplatesPrefix:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /player/FSS/SCTemplatesPrefix
      Value: !Ref QSS3KeyPrefix
      Type: String
      Description: Path for FSS Service catalog products

  # Product Definitions
  FSSAllInOneServiceCatalogProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Description:
        This template create the All in One FSS stack deployment for the service
        catalog.
      Name: File Storage Security All in One Template
      Owner: Trend Micro
      ProvisioningArtifactParameters:
        - Info:
            LoadTemplateFromURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}fss_allinone_service_catalog.template.yaml'
    DependsOn:
    - ChallengeBucket
    - SCTemplatesPrefix
  FSSStorageServiceCatalogProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Description: This template create the FSS Storage stack deployment for the service catalog.
      Name: File Storage Security Storage Stack Template
      Owner: Trend Micro
      ProvisioningArtifactParameters:
        - Info:
            LoadTemplateFromURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}fss_storage_service_catalog.template.yaml'
    DependsOn:
    - ChallengeBucket
    - SCTemplatesPrefix

  # Product IDs
  FSSAllInOneProductID:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "FSSAllInOneProductID"
      Value: !Ref FSSAllInOneServiceCatalogProduct
      Type: String
  FSSStorageProductID:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "FSSstoragestackProductID"
      Value: !Ref FSSStorageServiceCatalogProduct
      Type: String

  # Launch Role Constraints
  FSSAllInOneLaunchRoleConstraint:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    DependsOn: FSSAllInOneProductAssociation
    Properties:
      PortfolioId: !Ref PlayerServiceCatalogPortfolio
      ProductId: !Ref FSSAllInOneServiceCatalogProduct
      RoleArn: !Ref ServiceCatalogLaunchRoleArn
  FSSStorageLaunchRoleConstraint:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    DependsOn: FSSStorageProductAssociation
    Properties:
      PortfolioId: !Ref PlayerServiceCatalogPortfolio
      ProductId: !Ref FSSStorageServiceCatalogProduct
      RoleArn: !Ref ServiceCatalogLaunchRoleArn

  # Portfolio Associations
  FSSAllInOneProductAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref PlayerServiceCatalogPortfolio
      ProductId: !Ref FSSAllInOneServiceCatalogProduct
  FSSStorageProductAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref PlayerServiceCatalogPortfolio
      ProductId: !Ref FSSStorageServiceCatalogProduct
