AWSTemplateFormatVersion: 2010-09-09
Description: tdc-2022-techday-2 Cloud One File Storage Security S3 Buckets

Resources:
  FSSS3BucketObjLambda:
    Type: AWS::S3::Bucket
  FSSS3BucketObjLambdaPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FSSS3BucketObjLambda
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Action:
              - "s3:GetObject"
              - "s3:GetObjectTagging"
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${FSSS3BucketObjLambda}/*'
            Principal: '*'

Outputs:
  FSSS3BucketObjLambdaName:
    Value: !Ref FSSS3BucketObjLambda
    Description: S3 Bucket used in the challenge
  FSSS3BucketObjLambdaURL:
    Value: !Join ['', ['https://', !GetAtt [FSSS3BucketObjLambda, DomainName]]]
    Description: URL of S3 bucket to be use in the challenge
