AWSTemplateFormatVersion: 2010-09-09
Description: >
  Adds FSS CloudFormation templates to the Player's Service Catalog.

Parameters:
  # Service Catalog related
  PlayerServiceCatalogPortfolio:
    Type: String
  ServiceCatalogLaunchRoleArn:
    Type: String

Resources:
  FSSAllInOneServiceCatalogProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Description: This template create the All in One FSS stack deployment for the service catalog.
      Name: File Storage Security All in One Template
      Owner: Trend Micro
      ProvisioningArtifactParameters:
        - Info:
            LoadTemplateFromURL: "https://raw.githubusercontent.com/trendmicro/cloudone-filestorage-deployment-templates/master/aws/FSS-All-In-One.template"

  FSSAllInOneProductID:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "FSSAllInOneProductID"
      Value: !Ref FSSAllInOneServiceCatalogProduct
      Type: String

  FSSAllInOneProductAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref PlayerServiceCatalogPortfolio
      ProductId: !Ref FSSAllInOneServiceCatalogProduct

  FSSAllInOneLaunchRoleConstraint:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    DependsOn: FSSAllInOneProductAssociation
    Properties:
      PortfolioId: !Ref PlayerServiceCatalogPortfolio
      ProductId: !Ref FSSAllInOneServiceCatalogProduct
      RoleArn: !Ref ServiceCatalogLaunchRoleArn  
