AWSTemplateFormatVersion: 2010-09-09
Description: >
  This is the Day 2 main stack. It will be created whenever Wrinkles is ran.

Parameters:
  # Overall
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: techday-2021-2
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), dots(.) and forward slash (/).
    Default: challenges/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), dots(.) and
      forward slash (/).
    Type: String

  #### EXAMPLES BELOW!! ####

#   #Day 1 Outputs
#   WireupSnsTopic:
#     Type: String
#     Description: WireupSNSTopic for WS (from Day 1)
#   AppUrl:
#     Type: String
#     Description: AppUrl Output for AppSec (from Day 1)
#   ConformitySNSTopic:
#     Type: String
#     Description: Conformity SNS Topic (From Day 1)

#   # WS Task 1
#   DSA1InstanceId:
#     Type: String
#     Description: EC2 instance id for the victim.
#   DSA2InstanceId:
#     Type: String
#     Description: EC2 instance id for the attacker
#   ChallengeEC2Subnet:
#     Type: String
#     Description: Subnet to Launch EC2s into (from Day 1)
#   Day1InstanceNameTag:
#     Type: String
#     Default: 'DSA1'
#   Day2InstanceNameTag:
#     Type: String
#     Default: 'Test'

#   # All Challenges
#   S3ObjectName:
#     Type: String
#     Default: 'completed'
#   # WS SMM Challenge Answer Checker
#   SSMS3ObjectPrefix:
#     Type: String
#     Default: 'ssm/'
#   SSMFunctionName:
#     Type: String
#     Default: 'ChallengeWSSSM'
#   # WR Challenge Answer Checker
#   WRSS3ObjectPrefix:
#     Type: String
#     Default: 'wr/'
#   # IM Challenge Answer Checker
#   IMS3ObjectPrefix:
#     Type: String
#     Default: 'im/'
#   # LI Challenge Answer Checker
#   LIS3ObjectPrefix:
#     Type: String
#     Default: 'li/'
#   # WS Unified Security Events Checker
#   SecurityEventsFunctionName:
#     Type: String
#     Default: 'ChallengeWSSecurityEvents'

#   # Conformity SNS Checker
#   CCS3ObjectPrefix:
#     Type: String
#     Default: 'conformity/'
#     Description: Don't forget the "/" at the end of the prefix!
#   ConformityMessage:
#     Type: String
#     Default: Test Message from Cloud Conformity
#     Description: The message that is expected in SNS to validate the answer.
#   ConformityNCheckerFunctionName:
#     Type: String
#     Default: ConformityChallenge
#     Description: This name is provided by Amanda - checks s3 for score flag

#   # Application Security Day2
#   AttackFunctionName:
#     Default: AppSecTaskChecker
#     Description: A value that is agreed ahead with Amanda
#     Type: String

#   # File Storage Security Day 2
#   FSSBucketName:
#     Type: String
#     Description: Bucket used for FSS challenge on day 1.
#   FSSMalwareFileName:
#     Type: String
#     Description: File name given to the eicar file when dropped to the bucket.
#     Default: notmalware
#   FSSMalwareCheckerFunctionName:
#     Type: String
#     Description: Whatever name Amanda says this function needs to have.
#     Default: FssChallenge

#   PlayerGroupName:
#     Type: String

#   # Service Catalog
#   PlayerServiceCatalogPortfolio:
#     Type: String
#   ServiceCatalogLaunchRoleArn:
#     Type: String

#   # Apex One
#   ApexOneClient4InstanceId:
#     Type: String

Resources: 

  SampleBucket:
    Type: AWS::S3::Bucket

#   SampleDay2:
#     Type: AWS::CloudFormation::Stack
#     Properties:
#       Parameters:
#         PlayerServiceCatalogPortfolio: !Ref PlayerServiceCatalogPortfolio
#         ServiceCatalogLaunchRoleArn: !Ref ServiceCatalogLaunchRoleArn
#       TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}example/templates/day2_main.template.yaml'

#   WSDay2:
#     Type: AWS::CloudFormation::Stack
#     Properties:
#       Parameters:
#         WireupSnsTopic: !Ref WireupSnsTopic
#         QSS3BucketName: !Ref QSS3BucketName
#         QSS3KeyPrefix: !Sub ${QSS3KeyPrefix}/workload_security/
#         DSA1InstanceId: !Ref DSA1InstanceId
#         DSA2InstanceId: !Ref DSA2InstanceId
#         ChallengeEC2Subnet: !Ref ChallengeEC2Subnet
#         Day1InstanceNameTag: !Ref Day1InstanceNameTag
#         Day2InstanceNameTag: !Ref Day2InstanceNameTag
#         S3ObjectName: !Ref S3ObjectName
#         SSMS3ObjectPrefix: !Ref SSMS3ObjectPrefix
#         SSMFunctionName: !Ref SSMFunctionName
#         WRSS3ObjectPrefix: !Ref WRSS3ObjectPrefix
#         IMS3ObjectPrefix: !Ref IMS3ObjectPrefix
#         LIS3ObjectPrefix: !Ref LIS3ObjectPrefix
#         SecurityEventsFunctionName: !Ref SecurityEventsFunctionName
#         PlayerGroupName: !Ref PlayerGroupName
#       TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}workload_security/templates/WS_day2.template.yaml'

#   ConformityDay2:
#     Type: AWS::CloudFormation::Stack
#     Properties:
#       Parameters:
#         ConformitySNSTopic: !Ref ConformitySNSTopic
#         QSS3BucketName: !Ref QSS3BucketName
#         CCS3ObjectPrefix: !Ref CCS3ObjectPrefix
#         ConformityMessage: !Ref ConformityMessage
#         ConformityNCheckerFunctionName: !Ref ConformityNCheckerFunctionName
#         QSS3KeyPrefix: !Sub ${QSS3KeyPrefix}/conformity/
#       TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}conformity/templates/Conformity_day2.template.yaml'

#   NSDay2:
#     Type: AWS::CloudFormation::Stack
#     Properties:
#       Parameters:
#         AppUrl: !Ref AppUrl
#         AttackFunctionName: !Ref AttackFunctionName
#         QSS3BucketName: !Ref QSS3BucketName
#         QSS3KeyPrefix: !Sub ${QSS3KeyPrefix}/network_security/
#       TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}network_security/templates/NS_day2.template.yaml'

#   CSDay2:
#     Type: AWS::CloudFormation::Stack
#     Properties:
#       Parameters:
#         AppUrl: !Ref AppUrl
#         AttackFunctionName: !Ref AttackFunctionName
#         QSS3BucketName: !Ref QSS3BucketName
#         QSS3KeyPrefix: !Sub ${QSS3KeyPrefix}/container_security/
#       TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}network_security/templates/CS_day2.template.yaml'

#   OSSDay2:
#     Type: AWS::CloudFormation::Stack
#     Properties:
#       Parameters:
#         AppUrl: !Ref AppUrl
#         AttackFunctionName: !Ref AttackFunctionName
#         QSS3BucketName: !Ref QSS3BucketName
#         QSS3KeyPrefix: !Sub ${QSS3KeyPrefix}/open_source_security/
#       TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}network_security/templates/OSS_day2.template.yaml'

#   FSSDay2:
#     Type: AWS::CloudFormation::Stack
#     Properties:
#       Parameters:
#         BucketName: !Ref FSSBucketName
#         MalwareFileName: !Ref FSSMalwareFileName
#         MalwareCheckerFunctionName: !Ref FSSMalwareCheckerFunctionName
#         QSS3BucketName: !Ref QSS3BucketName
#         QSS3KeyPrefix: !Sub ${QSS3KeyPrefix}/file_storage_security/
#       TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}file_storage_security/templates/FSS_day2.template.yaml'

#   ServiceCatalogProductsDay2Stack:
#     Type: AWS::CloudFormation::Stack
#     Properties:
#       Parameters:
#         QSS3BucketName: !Ref QSS3BucketName
#         QSS3KeyPrefix: !Sub ${QSS3KeyPrefix}/templates/
#         PlayerServiceCatalogPortfolio: !Ref PlayerServiceCatalogPortfolio
#         ServiceCatalogLaunchRoleArn: !Ref ServiceCatalogLaunchRoleArn
#       TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/templates/day2_service_catalog_products.template.yaml'
#       TimeoutInMinutes: 10

#   #Apex One
#   ApexOneDay2:
#     Type: AWS::CloudFormation::Stack
#     Properties:
#       Parameters:
#         Client4InstanceId: !Ref ApexOneClient4InstanceId
#       TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}apexone/templates/apex_one_day2.template.yaml'

# #Outputs:
#   #C1 Day2 Outputs
#   #Conformity Day 2 Outputs
#   #Application Security Day 2 Outputs
