AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys 1 challenge team

Resources:

  Main:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://tdc-challenges.s3.amazonaws.com/SOME-PATH-TO-CHALLENGE-ROOT/templates/main.template.yaml'
      Parameters:
        QSS3BucketName: tdc-challenges
        QSS3KeyPrefix: SOME-PATH-TO-CHALLENGE-ROOT/
        Param1: 'HARDCODED'
        Param2: 'HARDCODED'

# Outputs:
#   Output1:
#     Value: !GetAtt Main.Outputs.Output1
#     Description: This is Output1

#   Output2:
#     Value: !GetAtt Main.Outputs.Output2
#     Description: This is Output2

#   Output3:
#     Value: !GetAtt Main.Outputs.Output3
#     Description: This is Output3

#   Output4:
#     Value: !GetAtt Main.Outputs.Output4
#     Description: This is Output4
