AWSTemplateFormatVersion: 2010-09-09
Description: >
  This is the post onboarding stack. It will be created whenever Wrinkles is ran.

Parameters:
  # Overall
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: techday-2021-2
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), dots(.) and forward slash (/).
    Default: challenges/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), dots(.) and
      forward slash (/).
    Type: String

Resources: 

  # Builds V1 Scoring 
  V1Scoring:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}challenges/vision_one/templates/v1so_score.template.yaml'

# SamplePostOnboard:
#     Type: AWS::CloudFormation::Stack
#     Properties:
#       Parameters:
#         PlayerServiceCatalogPortfolio: !Ref PlayerServiceCatalogPortfolio
#         ServiceCatalogLaunchRoleArn: !Ref ServiceCatalogLaunchRoleArn
#         QSS3KeyPrefix: !Sub '${QSS3KeyPrefix}/example/'
#       TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}example/templates/post_onboarding.template.yaml'

# #Outputs:
#   #C1 Day2 Outputs
#   #Conformity Day 2 Outputs
#   #Application Security Day 2 Outputs
