AWSTemplateFormatVersion: 2010-09-09
Description: >
  EC2 Victim Server with Tomcat Vulnerable Application (Log4Shell)

Parameters:
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Description: Update to where you hold the scripts. S3 bucket name for the Tech Day assets. Quick Start bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/_]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Description: Update to where you hold the scripts. S3 bucket name for the Tech Day assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  LatestAMIID:
    Description: "Latest AMI ID for Amazon Linux 2"
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  VPC:
    Type: AWS::EC2::VPC::Id
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
  AllowIP:
    Type: String

Resources:
  VictimSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
        GroupDescription: "Victim Log4Shell Security Group"
        VpcId: !Ref VPC
        Tags:
        - Key: Name
          Value: log4shellSecGroup
  VictimSGBaseIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref VictimSecurityGroup
      IpProtocol: tcp
      FromPort: 8080
      ToPort: 8080
      CidrIp: !Ref AllowIP

  VictimLog4ShellRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: /

  VictimLog4ShellProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - !Ref VictimLog4ShellRole

  VictimLog4Shell:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref VictimLog4ShellProfile
      ImageId: !Ref LatestAMIID
      InstanceType: m5.large
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - Ref: VictimSecurityGroup
          SubnetId:
            Ref: PublicSubnet1
      Tags:
      - Key: Name
        Value: VictimLog4Shell
      - Key: PlayerSsmAccess
        Value: "false"
      - Key: PlayerSsmDistributorAccess
        Value: "true"
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            wget https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}vulnerable_app.zip -P /home/ec2-user/
            unzip /home/ec2-user/vulnerable_app.zip -d /home/ec2-user/
            yum install -y java-1.8.0-openjdk-devel
            echo "Creating Tomcat user..."
            useradd -m -U -d /opt/tomcat/ -s /bin/false tomcat
            echo "Downloading Tomcat.."
            wget -qO- https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.3/bin/apache-tomcat-8.5.3.tar.gz | eval $SUDO tar xvz -C /opt/tomcat/ --strip-components=1
            echo "Configuring Tomcat.."
            chown -R tomcat: /opt/tomcat/
            chmod +x /opt/tomcat/bin/*.sh
            echo "
            [Unit]
            Description=Apache Tomcat Web Application Container
            After=network.target
            [Service]
            Type=forking
            Environment=JAVA_HOME="/"
            Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
            Environment=CATALINA_HOME=/opt/tomcat/
            Environment=CATALINA_BASE=/opt/tomcat/
            Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
            Environment='JAVA_OPTS=-Dcom.sun.jndi.ldap.object.trustURLCodebase=true -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Djava.awt.headless=true'
            ExecStart=/opt/tomcat/bin/startup.sh
            ExecStop=/opt/tomcat/bin/shutdown.sh
            User=tomcat
            Group=tomcat
            UMask=0007
            RestartSec=10
            Restart=always
            [Install]
            WantedBy=multi-user.target
            " | tee /etc/systemd/system/tomcat.service
            echo "Starting Tomcat..."
            systemctl daemon-reload
            systemctl start tomcat
            systemctl enable tomcat
            systemctl stop log4j-cve-2021-44228-hotpatch
            systemctl disable log4j-cve-2021-44228-hotpatch
            rm -rf /opt/tomcat/webapps/*
            cp /home/ec2-user/log4shell-* /opt/tomcat/webapps/ROOT.war
            systemctl restart tomcat
            
Outputs:
  Log4ShellSite:
    Description: Tomcat Web App with Log4Shell Vulnerability.
    Value: !Sub http://${VictimLog4Shell.PublicDnsName}:8080
  Log4ShellPublicDNSName:
    Description: Public DNS Name for the Victim Log4Shell Server.
    Value: !GetAtt VictimLog4Shell.PublicDnsName
