AWSTemplateFormatVersion: 2010-09-09
Description: >
  EC2 Victim Server with Tomcat Vulnerable Application (Log4Shell)

Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
  AllowIP:
    Type: String

Resources:
  VictimSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
        GroupDescription: "Victim Log4Shell Security Group"
        VpcId: !Ref VPC
        Tags:
        - Key: Name
          Value: log4shellSecGroup
  VictimSGBaseIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref VictimSecurityGroup
      IpProtocol: tcp
      FromPort: 8080
      ToPort: 8080
      CidrIp: !Ref AllowIP

  VictimLog4ShellRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: /

  VictimLog4ShellProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - !Ref VictimLog4ShellRole

  VictimLog4Shell:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref VictimLog4ShellProfile
      ImageId: "ami-0022f774911c1d690"
      InstanceType: t3.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - Ref: VictimSecurityGroup
          SubnetId:
            Ref: PublicSubnet1
      Tags:
      - Key: Name
        Value: VictimLog4Shell
      - Key: PlayerSsmAccess
        Value: "true"
      UserData:
        Fn::Base64: |
            #!/bin/bash
            yum update -y
            yum install -y git
            git clone https://github.com/kozmer/log4j-shell-poc.git /home/ec2-user/log4j-shell-poc/
            yum install -y java-1.8.0-openjdk-devel
            TOMCAT_HOME="/opt/tomcat/"
            echo "Creating Tomcat user..."
            useradd -m -U -d ${TOMCAT_HOME} -s /bin/false tomcat
            echo "Downloading Tomcat.."
            wget -qO- https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.3/bin/apache-tomcat-8.5.3.tar.gz | eval $SUDO tar xvz -C ${TOMCAT_HOME}/ --strip-components=1
            echo "Configuring Tomcat.."
            chown -R tomcat: ${TOMCAT_HOME}
            chmod +x ${TOMCAT_HOME}/bin/*.sh
            echo "
            [Unit]
            Description=Apache Tomcat Web Application Container
            After=network.target
            [Service]
            Type=forking
            Environment=JAVA_HOME="/"
            Environment=CATALINA_PID=${TOMCAT_HOME}/temp/tomcat.pid
            Environment=CATALINA_HOME=${TOMCAT_HOME}
            Environment=CATALINA_BASE=${TOMCAT_HOME}
            Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
            Environment='JAVA_OPTS=-Dcom.sun.jndi.ldap.object.trustURLCodebase=true -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Djava.awt.headless=true'
            ExecStart=${TOMCAT_HOME}/bin/startup.sh
            ExecStop=${TOMCAT_HOME}/bin/shutdown.sh
            User=tomcat
            Group=tomcat
            UMask=0007
            RestartSec=10
            Restart=always
            [Install]
            WantedBy=multi-user.target
            " | tee /etc/systemd/system/tomcat.service
            echo "Starting Tomcat..."
            systemctl daemon-reload
            systemctl start tomcat
            systemctl enable tomcat
            systemctl stop log4j-cve-2021-44228-hotpatch
            systemctl disable log4j-cve-2021-44228-hotpatch
            rm -rf /opt/tomcat/webapps/*
            cp /home/ec2-user/log4j-shell-poc/target/log4shell-* /opt/tomcat/webapps/ROOT.war
            systemctl restart tomcat
            
Outputs:
  Log4ShellSite:
    Description: Tomcat Web App with Log4Shell Vulnerability.
    Value: !Sub http://${VictimLog4Shell.PublicDnsName}:8080
  Log4ShellPrivateDNSName:
    Description: Private DNS Name for the Victim Log4Shell Server.
    Value: !GetAtt VictimLog4Shell.PrivateDnsName
