AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys the snyk-monitor helm chart into an existing kubernetes cluster (qs-1qqod7mii)"
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Deploy into an existing EKS cluster"
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Snyk monitor for EKS configuration
        Parameters:
          - KubeClusterName
          - SnykIntegrationId
          - Namespace
    ParameterLabels:
      KubeClusterName:
        default: EKS cluster name
      SnykIntegrationId:
        default: Snyk integration ID
      Namespace:
        default: Namespace
Parameters:
  KubeClusterName:
    Type: String
    Description: Name of the EKS cluster to deploy Snyk into.
  SnykIntegrationId:
    Type: String
    AllowedPattern: '[a-z0-9-]{36}'
    MinLength: 36
    Description: 'Snyk Kubernetes integration ID. This must be obtained from the Snyk console. For more information, see https://support.snyk.io/hc/en-us/articles/360003916158-Install-the-Snyk-controller-with-Helm.'
  Namespace:
    Type: String
    Default: snyk-monitor
    Description: '(Optional) Kubernetes namespace to deploy the Snyk controller into.'
Resources:
  SnykNamespace:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref KubeClusterName
      Namespace: default
      Manifest: !Sub |
        kind: Namespace
        apiVersion: v1
        metadata:
          name: ${Namespace}
  SnykSecret:
    Type: "AWSQS::Kubernetes::Resource"
    DependsOn: SnykNamespace
    Properties:
      ClusterName: !Ref KubeClusterName
      Namespace: !Ref Namespace
      Manifest: !Sub
        - |
          kind: Secret
          apiVersion: v1
          metadata:
            name: snyk-monitor
          type: Opaque
          data:
            dockercfg.json: ${DockerCfg}
            integrationId: ${IntegrationId}
        - DockerCfg: !Base64 "{}"
          IntegrationId: {'Fn::Base64': !Ref SnykIntegrationId}
  SnykHelmChart:
    Type: "AWSQS::Kubernetes::Helm"
    DependsOn: SnykSecret
    Properties:
      ClusterID: !Ref KubeClusterName
      Repository: https://snyk.github.io/kubernetes-monitor/
      Namespace: !Ref Namespace
      Chart: snyk-charts/snyk-monitor
      Name: snyk-monitor
      Values:
        clusterName: !Ref KubeClusterName
Outputs:
  SnykReleaseName:
    Value: snyk-monitor
