version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - echo ACCOUNT_ID=$ACCOUNT_ID
      - echo SERVICE_NAME=$SERVICE_NAME
      - echo CURRENT_ENV=$CURRENT_ENV
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/fss-attack
      - IMAGE_TAG=tdc_2022_2_fssAttack
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo IMAGE_TAG=$IMAGE_TAG
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
discard-paths: yes