AWSTemplateFormatVersion: 2010-09-09
Description: Set up Network Security service catalog product

Parameters:
  QSS3BucketName:
    Type: String
  QSS3KeyPrefix:
    Type: String
  PlayerServiceCatalogPortfolio:
    Type: String
  ServiceCatalogLaunchRoleArn:
    Type: String

Resources:
  PlayerNetworkSecurityServiceCatalogProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Description: "Create the Cloud Account for Cloud One Network Security"
      Name: "Cloud One Network Security Cross Account Role"
      Owner: "Trend Micro"
      ProvisioningArtifactParameters:
        - Info:
            LoadTemplateFromURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/network_security_xaccountiamrole.yaml'

  NetworkSecurityRolePortfolioProductAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref PlayerServiceCatalogPortfolio
      ProductId: !Ref PlayerNetworkSecurityServiceCatalogProduct

  NetworkSecurityRoleLaunchRoleConstraint:
    DependsOn: NetworkSecurityRolePortfolioProductAssociation
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    Properties:
      PortfolioId: !Ref PlayerServiceCatalogPortfolio
      ProductId: !Ref PlayerNetworkSecurityServiceCatalogProduct
      RoleArn: !Ref ServiceCatalogLaunchRoleArn

  NetworkSecurityLaunchTemplateConstraint:
    DependsOn: NetworkSecurityRolePortfolioProductAssociation
    Type: AWS::ServiceCatalog::LaunchTemplateConstraint
    Properties:
      PortfolioId: !Ref PlayerServiceCatalogPortfolio
      ProductId: !Ref PlayerNetworkSecurityServiceCatalogProduct
      Rules: !Join
        - ""
        - - '{"Api": {"Assertions": [{"Assert": {"Fn::Not": [{"Fn::Contains": [[""],{"Ref": "CloudOneApiKey"}]}]},"AssertDescription": "Please enter your API Key"}]}}'
