AWSTemplateFormatVersion: 2010-09-09

Resources:
  C1WSEppOfflineCheckScoreRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  C1WSEppOfflineCheckScoreLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: C1WSEppOfflineCheck
      Code: 
        ZipFile: |
          import requests as rq
          import json as js
          import boto3
          
          print('Loading function')
          
          def get_ssm_params(*keys, region='us-east-1'):
              result = {}
              ssm = boto3.client('ssm', region)
              response = ssm.get_parameters(
                  Names=keys,
                  WithDecryption=True,
              )
              for p in response['Parameters']:
                  result[p['Name']] = p['Value']
              return result
          
          def lambda_handler(event, context):
              parameter = get_ssm_params("/player/C1/c1ApiKey")
              URL_search_policy = "https://workload.trend-us-1.cloudone.trendmicro.com/api/policies"
              key = parameter["/player/C1/c1ApiKey"]
              APIkey = "Apikey " + key
              header = {
              "Content-Type": "application/json",
              "Authorization" : APIkey,
              "api-version": "v1",
              }
          
              r = rq.get(URL_search_policy, headers=header)
              search_policy = js.loads(r.text)
              for policy in search_policy["policies"]:
                  if policy["policySettings"]["antiMalwareSettingOfflineScheduledScanEnabled"]["value"] == "true" and policy["name"] == "usethispolicy":
                      return(True)
                  return(False) 
      Handler: index.lambda_handler
      Role: !GetAtt C1WSEppOfflineCheckScoreRole.Arn
      Runtime: python3.7
      MemorySize: 512
      Environment:
        Variables:
    DependsOn:
      - scoreroleday1task1C1WS
Outputs:
  C1WSScoreLambdarday1task1Name:
    Value:
      Ref: C1WSScoreLambdarday1task1
