name: Build Dev Environment

env:
  BUCKET_NAME: 'techday-2022-2-dev'
  AWS_REGION: 'us-east-1'

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Commit hash to build.'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  sync-and-deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.name }}
    - name: Replace QSS3BucketName and QSS3KeyPrefix
      shell: bash
      run: |
        pip install jq yq
        sed -e '/QSS3KeyPrefix/!b' -e ':a' -e "s/Default: $(cat templates/main.template.yaml | yq .Parameters.QSS3KeyPrefix.Default | sed -e 's/[\/&]/\\&/g')/Default: ${{ github.event.inputs.name }}\//;t trail" -e 'n;ba' -e ':trail' -e 'n;btrail' templates/main.template.yaml > templates/TEMP.main.template.yaml && sed -e '/QSS3BucketName/!b' -e ':a' -e "s/Default: $(cat templates/TEMP.main.template.yaml | yq -r .Parameters.QSS3BucketName.Default)/Default: ${{ env.BUCKET_NAME }}/;t trail" -e 'n;ba' -e ':trail' -e 'n;btrail' templates/TEMP.main.template.yaml > templates/main.template.yaml
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.git/github' 
      env:
        AWS_S3_BUCKET: ${{ env.BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_REGION }}
        DEST_DIR: ${{ github.event.inputs.name }}
    - name: Installing Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Deploy to Vending Machine
      env:
        CFN_URL: 'https://${{ env.BUCKET_NAME }}.s3.amazonaws.com/${{ github.event.inputs.name }}/templates/main.template.yaml'
        VM_API_KEY: ${{ secrets.VM_API_KEY }}
      working-directory: .github/workflows/setup-account-using-vending-machine
      run: |
        npm ci
        node setup-account-using-vending-machine.js