name: On Pull Request

env:
  BUCKET_NAME: 'techday-2022-1-staging'
  AWS_REGION: 'us-east-1'

on: pull_request

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF##*/})"
      id: extract_branch
    - uses: actions/checkout@master
    - name: Replace QSS3BucketName and QSS3KeyPrefix
      shell: bash
      run: |
        ls -lah
        pip install jq yq
        sed -e '/QSS3BucketName/!b' -e ':a' -e "s/Default: $(cat main.template.yaml | yq .Parameters.QSS3KeyPrefix.Default)/Default: BUCKET/;t trail" -e 'n;ba' -e ':trail' -e 'n;btrail' main.template.yaml > TEST.main.template.yaml && sed -e '/QSS3BucketName/!b' -e ':a' -e "s/Default: $(cat main.template.yaml | yq -r .Parameters.QSS3BucketName.Default)/Default: techday-2021-2-staging/;t trail" -e 'n;ba' -e ':trail' -e 'n;btrail' TEST.main.template.yaml > main.template.yaml
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.git/github' 
      env:
        AWS_S3_BUCKET: ${{ env.BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_REGION }}
        DEST_DIR: ${GITHUB_HEAD_REF##*/}
    - name: Installing Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Deploy to Vending Machine
      env:
        CFN_URL: 'https://${{ env.BUCKET_NAME }}.s3.amazonaws.com/${{ steps.extract_branch.outputs.branch }}/templates/main.template.yaml'
        VM_API_KEY: ${{ secrets.VM_API_KEY }}
      working-directory: .github/workflows/setup-account-using-vending-machine
      run: |
        npm ci
        node setup-account-using-vending-machine.js