name: On Pull Request

env:
  BUCKET_NAME: 'techday-2022-1-staging'
  AWS_REGION: 'us-east-1'

on: pull_request

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ env.BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_REGION }}
        DEST_DIR: ${{ steps.extract_branch.outputs.branch }}
    - name: Installing Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Deploy to Vending Machine
      env:
        CFN_URL: 'https://${{ env.BUCKET_NAME }}.s3.amazonaws.com/${{ steps.extract_branch.outputs.branch }}/templates/main.template.yaml'
        VM_API_KEY: ${{ secrets.VM_API_KEY }}
      working-directory: .github/workflows/setup-account-using-vending-machine
      run: |
        npm ci
        node setup-account-using-vending-machine.js