name: On Push

on: [push]

jobs:
  cloudformation-linter:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: cfn-lint
      uses: scottbrenner/cfn-lint-action@v2
      with:
        args: "--ignore-checks W E3012 E3005 -- challenge/[!eks]*/templates/*.template.yaml challenge/templates/*.yaml"
